-- MySQL Script generated by MySQL Workbench
-- Sun 12 Mar 2023 07:22:08 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club` (
  `CIF` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `FechaFund` DATE NULL DEFAULT NULL,
  `Descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `Camuflaje` VARCHAR(20) NULL DEFAULT NULL,
  `Escudo` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`CIF`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `miembro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miembro` (
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(15) NOT NULL,
  `Apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `FechaNac` DATE NULL DEFAULT NULL,
  `Telefono` VARCHAR(9) NOT NULL,
  `Mail` VARCHAR(30) NOT NULL,
  `Cuota` TINYINT(4) NULL DEFAULT NULL,
  `Alquiler` TINYINT(4) NULL DEFAULT NULL,
  `Foto` VARCHAR(250) NULL DEFAULT NULL,
  `Lider` TINYINT(4) NULL DEFAULT NULL,
  `CLUB_CIF` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `fk_MIEMBRO_CLUB1_idx` (`CLUB_CIF` ASC),
  CONSTRAINT `fk_MIEMBRO_CLUB1`
    FOREIGN KEY (`CLUB_CIF`)
    REFERENCES `club` (`CIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `club`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `club` (`CIF`, `Nombre`, `FechaFund`, `Descripcion`, `Camuflaje`, `Escudo`) VALUES ('Z-00000000', 'INDIVIDUAL', '', '', NULL, NULL);
INSERT INTO `club` (`CIF`, `Nombre`, `FechaFund`, `Descripcion`, `Camuflaje`, `Escudo`) VALUES ('A-23038574', 'Grupo SEAL', '2018-07-07', 'Grupo SEAL almería Inspirado en DELTA USA', 'Multicam', 'https://scontent-mad2-1.xx.fbcdn.net/v/t39.30808-6/307175782_403868888580642_5980010012786327584_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=brAqzyK_tuYAX_leOc3&_nc_ht=scontent-mad2-1.xx&oh=00_AfA8T_YMsDSQXgA1qvv3szOLrZ9z0-WFXF_Z2SxHO0-vUw&oe=6412BC4E');
INSERT INTO `club` (`CIF`, `Nombre`, `FechaFund`, `Descripcion`, `Camuflaje`, `Escudo`) VALUES ('B-65489100', 'SWAT', '2015-05-20', 'Grupo con sede en la capital, más de 100 miembros', 'Bosocoso', 'https://amigosdelairsoft.org/wp-content/uploads/2021/04/swat-2.png');
INSERT INTO `club` (`CIF`, `Nombre`, `FechaFund`, `Descripcion`, `Camuflaje`, `Escudo`) VALUES ('C-30178416', 'Mad Pigs', '2019-09-09', 'Grupo de Adra, unidades de élite y jugadores experimentados', 'Negro Pitón', 'https://amigosdelairsoft.org/wp-content/uploads/2021/04/19956811_1923491474564861_3742805399260956807_o-300x300.jpg');
INSERT INTO `club` (`CIF`, `Nombre`, `FechaFund`, `Descripcion`, `Camuflaje`, `Escudo`) VALUES ('D-20418744', 'Tercio Alboran', '2010-12-01', 'El más veterano de todos, se mantiene activo nacional', 'Árido Español', 'https://amigosdelairsoft.org/wp-content/uploads/2021/04/tercio-alboran-2-250x300.jpg');

COMMIT;


-- -----------------------------------------------------
-- Data for table `miembro`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `miembro` (`DNI`, `Nombre`, `Apellidos`, `FechaNac`, `Telefono`, `Mail`, `Cuota`, `Alquiler`, `Foto`, `Lider`, `CLUB_CIF`) VALUES ('52106987G', 'Fernando', 'Martinez', '1979-04-16', '625879410', 'FerMan79@gmail.com', 1, 0, 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 1, 'D-20418744');
INSERT INTO `miembro` (`DNI`, `Nombre`, `Apellidos`, `FechaNac`, `Telefono`, `Mail`, `Cuota`, `Alquiler`, `Foto`, `Lider`, `CLUB_CIF`) VALUES ('62014789J', 'Jesús', 'Méndez', '1980-01-30', '641225588', 'gruposealalm@gmail.com', 0, 0, 'https://images.pexels.com/photos/15760437/pexels-photo-15760437.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 1, 'A-23038574');
INSERT INTO `miembro` (`DNI`, `Nombre`, `Apellidos`, `FechaNac`, `Telefono`, `Mail`, `Cuota`, `Alquiler`, `Foto`, `Lider`, `CLUB_CIF`) VALUES ('46512008R', 'Manuel', 'Uroz', '1971-09-13', '741023658', 'rangeralmeria@outlook.es', 1, 0, 'https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 1, 'B-65489100');
INSERT INTO `miembro` (`DNI`, `Nombre`, `Apellidos`, `FechaNac`, `Telefono`, `Mail`, `Cuota`, `Alquiler`, `Foto`, `Lider`, `CLUB_CIF`) VALUES ('26523016Z', 'Mario', 'Galvez', '2001-03-12', '600795600', 'margalvezsimarro@gmail.com', 0, 1, 'https://images.pexels.com/photos/15045042/pexels-photo-15045042.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 0, 'A-23038574');
INSERT INTO `miembro` (`DNI`, `Nombre`, `Apellidos`, `FechaNac`, `Telefono`, `Mail`, `Cuota`, `Alquiler`, `Foto`, `Lider`, `CLUB_CIF`) VALUES ('30852418D', 'Juan', 'Esteban', '2002-11-25', '658941003', 'juanest23@hotmail.com', 1, 1, 'https://images.pexels.com/photos/13872174/pexels-photo-13872174.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 0, 'Z-00000000');
INSERT INTO `miembro` (`DNI`, `Nombre`, `Apellidos`, `FechaNac`, `Telefono`, `Mail`, `Cuota`, `Alquiler`, `Foto`, `Lider`, `CLUB_CIF`) VALUES ('95874102I', 'Felipe', 'Torres', '1997-10-17', '648100258', 'ferelgrande@gmail.com', 1, 1, 'https://images.pexels.com/photos/3031396/pexels-photo-3031396.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 1, 'C-30178416');

COMMIT;

